### ISSUE TITLE
It seems that the demo cannot be accessed properly?

### ISSUE THREAD

**Issue by pixeli99** [baaivision/Emu#1]

**Comment by youxiho1** [comment]
Same. It seems that it actually generates no response... Very excited about this work, waiting for bug fix lol

**Comment by yqy2001** [comment]
Thank you for your attention and interest to our work. The bug is fixed, please check it out. 

If the issue persists, you may consider using either Chrome or Firefox as an alternative browser.

**Comment by yqy2001** [comment]
The demo is now accessible. It was disabled for debugging purposes, sorry for the inconvenience.
