### ISSUE TITLE
Inference with video

### ISSUE THREAD

**Issue by shahkalp09** [baaivision/Emu#10]
Hi, you guys have done great work.
 can you guide me on how to make inferences with video input? and are you planning to push the training and finetuning code for this model?

**Comment by yqy2001** [comment]
Hi, thanks you for appreciating our work. We've added an video inference example, please check out the code [here](https://github.com/baaivision/Emu/blob/36d7ce7eb07272be3241086df0e37b0bac1889e5/inference.py#L170).

We plan to release all Emu related materials listed [here](https://github.com/baaivision/Emu/blob/36d7ce7eb07272be3241086df0e37b0bac1889e5/README.md?plain=1#L62), but it will take some time. Besides, we will release a stronger **Emu** together with the image decoder this or next week, please stay tuned!

Thank you.

**Comment by shahkalp09** [comment]
Ok sure, Thanks for the reply!
