### ISSUE TITLE
question about the pretrained weights for image encoder EVA-clip

### ISSUE THREAD

**Issue by Lechatelia** [baaivision/Emu#13]
Hey~
Thanks for your amazing work!
I have a question about your pretrianed weights in your Emu's training.
It seems that you used  a 1b version of eva-02-clip, as mentioned in your paper.
Also the [eva-clip-g-14-x](https://github.com/baaivision/Emu/blob/main/models/Emu-14B.json) is also found in your code.
However, I cound not find the pre-trained weights for the small g (1b) version of eva-02-clip, neithr  in eval-clip official  github repo or  in huggingface modelzoo. Instead I found the 1b version of eva01-clip (not 02) in https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA01_CLIP_g_14_psz14_s11B.pt.
Could provide the specific link of your used eva-clip model weights?
Please forgive me if I am wrong.

**Comment by yqy2001** [comment]
Thank you for pointing this out. We used EVA-**01**-CLIP-g in Emu, but this was erroneously reported in our paper. Sorry for any confusion this may have caused. We will correct this typo in the next version.

This is the link to the EVA-CLIP we use: https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA01_CLIP_g_14_plus_psz14_s11B.pt
