### ISSUE TITLE
Image Generation 

### ISSUE THREAD

**Issue by jshilong** [baaivision/Emu#18]
Thanks for your amazing work
Is there any plan to release the image generation part?

**Comment by yqy2001** [comment]
Thank you for your interest in our work. The image generation part is released and an [inference example](https://github.com/baaivision/Emu/blob/def850fa860162264bfbe030e23297f2a8776849/README.md?plain=1#L65) is provided. Please check it out.

**Comment by jshilong** [comment]
> Thank you for your interest in our work. The image generation part is released and an [inference example](https://github.com/baaivision/Emu/blob/def850fa860162264bfbe030e23297f2a8776849/README.md?plain=1#L65) is provided. Please check it out.

Thanks！
