### ISSUE TITLE
LLama的license问题

### ISSUE THREAD

**Issue by lj163ucas** [baaivision/Emu#19]
https://github.com/baaivision/Emu/blob/8edd8c24a97564c55901fbc7ce671abec2e71042/README.md?plain=1#L39C1-L39C1
这里放的是llama2的license，论文里似乎使用的是llama1吧？所以，应该是不可以商用的吧。

那请问是否有计划基于llama2可商用版本进行重新训练呢？

**Comment by yqy2001** [comment]
Thank you for pointing out this issue. Yep current Emu is subjected to LLaMA-1's license and is not allowed for commercial use. We have plan to train a new Emu based on LLaMA-2.
