### ISSUE TITLE
Image blending prompt

### ISSUE THREAD

**Issue by vishaal27** [baaivision/Emu#2]
Hey, thanks so much for releasing your great paper and making the code and weights public. I am quite interested in playing around with the model for the task of image blending. Could you please provide the exact prompt used for the image blending results in Figure 1 of the paper?

**Comment by yqy2001** [comment]
No prompt is needed for image blending :). To blend two images, simply concatenate them into a sequence, and append an [IMG] token to denote the start of the image to be generated:

$$
\texttt{[IMG]image1[/IMG][IMG]image2[/IMG][IMG]}
$$

, then feed this sequence into pretrained Emu, which will auto-regressively generates 32 image embeddings that could be further decoded into realistic blended image.

Please note that we have not released the code for auto-regressive image generation and the weights of the image decoder. However, you can play with our [demo](http://218.91.113.230:9002/) now, which supports this function.

Thank you for your interest in our work.

**Comment by PeihaoChen** [comment]
Thanks for your amazing work! When will you release the code for auto-regressive image generation and the weights of the image decoder? Also, do you have a plan to release the training code? Thx!

**Comment by yqy2001** [comment]
We plan to release all of them, but it might take some time to do so. Thank you.
