### ISSUE TITLE
Inquire on the evaluation code

### ISSUE THREAD

**Issue by HenryHZY** [baaivision/Emu#24]
Hi @yqy2001 , thanks for your hard work. Do you have a schedule to release the evaluation code recently?

**Comment by yqy2001** [comment]
The evaluation code will be released in next several days. Thaks for your interest~

**Comment by yqy2001** [comment]
The evaluation code has been released. Please check it.

Thank you for your interest in our work.

**Comment by HenryHZY** [comment]
> The evaluation code has been released. Please check it.
> 
> 
> 
> Thank you for your interest in our work.

Thank you!
