### ISSUE TITLE
Plan of releasing YT-Storyboard-1B Dataset

### ISSUE THREAD

**Issue by sijeh** [baaivision/Emu#25]
Hi, Thanks for your great work, do you have the plan to release the YT-Storyboard-1B dataset?

**Comment by SlotherCui** [comment]
Thank you for your interest in our work. Due to copyright issues we cannot release the original data. We have provided the collection tools for [YT-Storyboad-1B dataset](https://github.com/baaivision/Emu/tree/main/data/yt-sb-1b). Please check it out.
