### ISSUE TITLE
Is there any smaller variants?

### ISSUE THREAD

**Issue by YifanXu74** [baaivision/Emu#26]
Hi, excellent work! 
I noticed that only the weight for a large model (14B) is available in the GitHub repository. Is it possible to provide weights for some smaller variants, such as the 7B model? I believe this would enable broader applications of this work.

**Comment by yqy2001** [comment]
Thank you for your interest in our work. We currently do not have plans to develop a smaller variant, and the smallest version available will remain at 14B. Sorry for any inconvenience this may have caused.

**Comment by YifanXu74** [comment]
OK. Thanks for the reply!
