### ISSUE TITLE
Create a demo on Hugging Face 

### ISSUE THREAD

**Issue by adeenayakup** [baaivision/Emu#4]
Hi!

Very cool work! It would be nice to have demo on the [Hugging Face Hub](https://huggingface.co/spaces) as well. 

This is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process in case you're interested. : )
 
Please let us know if you would be interested and if you have any questions.

**Comment by yqy2001** [comment]
Thanks for your guidance. We will deliver our demo on Hugging Face Hub soon.
