### ISSUE TITLE
Eval Dataset

### ISSUE THREAD

**Issue by jybxie123** [baaivision/Emu#41]
Hi, I have a question about the COCO dataset evaluation.
What' s the meaning in the benchmark/COCO/annotations/vqa_test.json and vqa_val_eval.json?
Or could you please give the link of these dependent datasets?

**Comment by zhangxiaosong18** [comment]
They are VQAv2 annotation files processed by [LAVIS](https://github.com/salesforce/LAVIS) and can be downloaded from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/vqa_val_eval.json and https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/vqa_test.json
