### ISSUE TITLE
何时支持中文？

### ISSUE THREAD

**Issue by zky001** [baaivision/Emu#49]

**Comment by Quan-Sun** [comment]
我们正在准备中英双语的版本，后面训练完成会第一时间更新。

**Comment by will-wiki** [comment]
@Quan-Sun 想问下这个中英双语版模型有大概的排期时间嘛

**Comment by Quan-Sun** [comment]
@will-wiki 目前已经准备好了部分数据，正在进行预训练，按目前的进度，顺利的话大概需要1个月的时间
