### ISSUE TITLE
The n_query and v_query in EMU2

### ISSUE THREAD

**Issue by Arsiuuu** [baaivision/Emu#50]
Thanks for the excellent work! 
I want to get the meaning of n_query and v_query. Why an image is worth 256 tokens while a video is worth 64? Could you please offer the codes of video inference? Thanks!

**Comment by ryanzhangfan** [comment]
Thanks for your interest in our work!

In instruct tuning phase, each image is represented by 256 tokens (`448 x 448` image -> EVA Visual Encoder -> `32 x 32` tokens -> average pooling -> `16 x 16` tokens), which is `n_query`. Each video frame is represented by 64 tokens(`448 x 448` image -> EVA Visual Encoder -> `32 x 32` tokens -> average pooling -> `8 x 8` tokens), which is `v_query`. 

More tokens often denotes stronger understanding ability. But if we use 256 tokens to represent each frame in the video, the context length will be too long, which will cost `n_frames x 256` tokens. Hence, we opted to compromise by using 64 tokens for video frames.

The v_query is specifically used in Emu2-Chat. In Emu2 and Emu2-Gen, all images and video frames is uniformly represented by `n_query=64` tokens.

We'll release detailed inference codes including chat template and video understanding inference in few days.
For video generation, we are organizing the inference code and plan to release it in the near future.

**Comment by Arsiuuu** [comment]
Thank you for your kind guidance~
I met the **CUDA OUT OF MEMORY** when I tried to inference **16** frames video on **one A100 80GB**, is this normal? the Should I use multi-GPU instead?

**Comment by ryanzhangfan** [comment]
Yes. For bf16 version of models, it is recommended to have at least 120GB GPU memory

**Comment by ryanzhangfan** [comment]
Yes. Generally, for the bf16 version of model, the model itself will occupy at least 70GB+ GPU memory. There are several ways to mitigate the OOM issue.

1. Use quantized version of model, which will only take ~22GB for model itself. Please follow the [instruction](https://github.com/baaivision/Emu/tree/main/Emu2#quantization) to enable int4 quantization.
2. Adjust the hyper parameters, e.g. decrease the `num_beams`.
3. If you want to leverage the full power of the model, it is recommended to use at least 120GB of GPU memory. Please follow the [instruction](https://github.com/baaivision/Emu/tree/main/Emu2#multi-gpu) to enable the multi-GPU inference.

p.s. For video understanding tasks, you prompt of video frames part should be organized as "[VIDEO][IMG]<image>x64[/IMG][IMG]<image>x64[/IMG][IMG]<image>x64[/IMG]...". The "<image>x64" part should be replaced by frame features after embed_tokens.

**Comment by Arsiuuu** [comment]
Oh, I got it. So I should modify:
`self.video_placeholder = DEFAULT_VIDEO_TOKEN + (DEFAULT_IMAGE_TOKEN * self.v_query + DEFAULT_IMG_END_TOKEN) * 16` and `video_idx = (input_ids == IMAGE)` in modeling_emu.py?

**Comment by ryanzhangfan** [comment]
Sry, I think I do not clarify clearly. What I want to point out is for video frames input, you should <b>prepend the special token</b> `[VIDEO]` before the first frame.

We recommend that you leave the `self.image_placeholder` and `self.video_placeholder` unchanged. As you can see, `video_placeholder` and `image_placeholder` are just placeholders. `<image>` and `[gIMG]` features will be replaced by image/frame features extracted by EVA Visual Encoder. The reason that we use different tokens `<image>` and `[gIMG]` for images and video frames separately is to facilitate subsequent feature replacement operation.

**Comment by Arsiuuu** [comment]
> Sry, I think I do not clarify clearly. What I want to point out is for video frames input, you should prepend the special token `[VIDEO]` before the first frame.
> 
> We recommend that you leave the `self.image_placeholder` and `self.video_placeholder` unchanged. As you can see, `video_placeholder` and `image_placeholder` are just placeholders. `<image>` and `[gIMG]` features will be replaced by image/frame features extracted by EVA Visual Encoder. The reason that we use different tokens `<image>` and `[gIMG]` for images and video frames separately is to facilitate subsequent feature replacement operation.

But in the original code, `self.video_placeholder = DEFAULT_IMG_TOKEN + DEFAULT_gIMG_TOKEN * self.v_query + DEFAULT_IMG_END_TOKEN` only get one frame. Are you telling me that I should use multiple video_placeholder like `[VIDEO][<VID_PLH>][<VID_PLH>][<VID_PLH>][<VID_PLH>][<VID_PLH>]……` in prompt and not modify what content that replace [<VID_PLH>]?

**Comment by ryanzhangfan** [comment]
> > Sry, I think I do not clarify clearly. What I want to point out is for video frames input, you should prepend the special token `[VIDEO]` before the first frame.
> > We recommend that you leave the `self.image_placeholder` and `self.video_placeholder` unchanged. As you can see, `video_placeholder` and `image_placeholder` are just placeholders. `<image>` and `[gIMG]` features will be replaced by image/frame features extracted by EVA Visual Encoder. The reason that we use different tokens `<image>` and `[gIMG]` for images and video frames separately is to facilitate subsequent feature replacement operation.
> 
> But in the original code, `self.video_placeholder = DEFAULT_IMG_TOKEN + DEFAULT_gIMG_TOKEN * self.v_query + DEFAULT_IMG_END_TOKEN` only get one frame. Are you telling me that I should use multiple video_placeholder like `[VIDEO][<VID_PLH>][<VID_PLH>][<VID_PLH>][<VID_PLH>][<VID_PLH>]……` in prompt and not modify what content that replace [<VID_PLH>]?

YES! For example, your codes should be like:
```
frame_num = 16
prompt =  "[VIDEO]" + "[<VID_PLH>]" * frame_num + "What happened in the video?"
frames = [Image.open(f"frame_{idx}.jpg").convert("RGB") for idx in range(frame_num)]

inputs = model.build_input_ids(
    text=[prompt],
    tokenizer=tokenizer,
    video=inputs,
)
outputs = model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    video=inputs["video"].to(torch.bfloat16),
)
```
Users might not extract 16 frames for all videos. So if you modify the `self.video_placeholder` with the deterministic number of frames, every time you want to change the frames number, you need to modify the source code again and restart the program again.

**Comment by Arsiuuu** [comment]
Thank you very much for your patient reply！Wish more impactful work from your team~
