### ISSUE TITLE
offline infer different from your demo.

### ISSUE THREAD

**Issue by xmy0916** [baaivision/Emu#54]
![image](https://github.com/baaivision/Emu/assets/43675899/f67bc2f0-79da-4ebb-bb66-d53219916bd7)
The output of the model is very short, even i set "answer more than xxx words" in the prompt doesn't help. here is my test code, any help please!
```python
from PIL import Image 
import requests
import torch 
from transformers import AutoModelForCausalLM, AutoTokenizer
from accelerate import init_empty_weights, infer_auto_device_map, load_checkpoint_and_dispatch

tokenizer = AutoTokenizer.from_pretrained("BAAI/Emu2-Chat") # "BAAI/Emu2-Chat"

with init_empty_weights():
     model = AutoModelForCausalLM.from_pretrained(
        "BAAI/Emu2-Chat", # "BAAI/Emu2-Chat"
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        cache_dir="./ckpt")  

device_map = infer_auto_device_map(model, max_memory={0:'50GiB',1:'50GiB',}, no_split_module_classes=['Block','LlamaDecoderLayer'])  
# input and output logits should be on same device
device_map["model.decoder.lm.lm_head"] = 0

model = load_checkpoint_and_dispatch(
    model, 
    './ckpt/models--BAAI--Emu2-Chat/snapshots/20ea30b04f8fee599cf97535e655c200df728501',
    device_map=device_map).eval()

frms = [
  "img1.jpg",
  "img2.jpg",
  "img3.jpg",
  "img4.jpg",
  "img5.jpg",
  "img6.jpg",
  "img7.jpg",
  "img8.jpg",
]

video = [Image.open(frm).convert('RGB') for frm in frms]

import time

start_time = time.time()
query = "{}Describe the video in details.".format("[<VID_PLH>]"*len(frms))


inputs = model.build_input_ids(
    text=[query],
    tokenizer=tokenizer,
    video=video

)

with torch.no_grad():
     outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        video=inputs["video"].to(torch.bfloat16),
        max_new_tokens=2048,
        length_penalty=-1)

output_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)

print("infer cost", time.time()-start_time)

output_text

```

**Comment by xmy0916** [comment]
after test on online demo, answer length are the same. close

**Comment by ryanzhangfan** [comment]
#### Chat Template
To use the Emu2-Chat, the inputs to the model should follow the chat template "\<SYSTEM MESSAGE\> [USER]: \<YOUR PROMPT\> [ASSISTANT]:". The system message and more detailed inputs construction codes can be found at [here](https://github.com/baaivision/Emu/blob/a0ff15d282629cce82b639dec26b364ae74c2864/Emu2/demo/frontend/libs/meta.py#L259)

#### Video Format
For video understanding tasks, the video frames part in you prompt should be organized as "**[VIDEO]**[\<VID_PLH\>][\<VID_PLH\>][\<VID_PLH\>]...". There should be a special token **[VIDEO]** before the first frame.

#### More Detailed Output
You may adjust your prompt to force the model to output more results. For example, "What happened in the video? Describe as many elements as possible.", etc.

**Comment by xmy0916** [comment]
> #### Chat Template
> To use the Emu2-Chat, the inputs to the model should follow the chat template "<SYSTEM MESSAGE> [USER]: <YOUR PROMPT> [ASSISTANT]:". The system message and more detailed inputs construction codes can be found at [here](https://github.com/baaivision/Emu/blob/a0ff15d282629cce82b639dec26b364ae74c2864/Emu2/emu/chat.py#L159)
> 
> #### Video Format
> For video understanding tasks, the video frames part in you prompt should be organized as "**[VIDEO]**[<VID_PLH>][<VID_PLH>][<VID_PLH>]...". There should be a special token **[VIDEO]** before the first frame.
> 
> #### More Detailed Output
> You may adjust your prompt to force the model to output more results. For example, "What happened in the video? Describe as many elements as possible.", etc.

Thanks!
