### ISSUE TITLE
啊这。。。。

### ISSUE THREAD

**Issue by qiezikuangge** [baaivision/Emu#58]
![image](https://github.com/baaivision/Emu/assets/50002441/2f31107e-8f0d-4a4f-bfdc-b56a4572998c)

**Comment by ryanzhangfan** [comment]
Maybe you can try the [fast demo](https://emu.ssi.plus), which is more faster and has less queue time.

**Comment by ryanzhangfan** [comment]
We have relaunched the huggingface demo. Now it can be used normally.
