### ISSUE TITLE
How to train few-shot ability?

### ISSUE THREAD

**Issue by jyC23333** [baaivision/Emu#60]
Hi, Wonderful work!

I'm wondering:
How many few-shot training items are used?
In pretrain or in instruct tuning?

**Comment by Quan-Sun** [comment]
Hi @jyC23333, we used [MMC4](https://github.com/allenai/mmc4) and [YT-SB-1B](https://github.com/baaivision/Emu/tree/main/Emu1/data/yt-sb-1b) as interleaved image/video-text data in pretraining stage, enhancing in-context learning abilities.

**Comment by jyC23333** [comment]
Thanks so much.
