### ISSUE TITLE
RuntimeError: shape mismatch

### ISSUE THREAD

**Issue by timwalls** [baaivision/Emu#62]
Honestly, I am sure there is something obvious I am missing here, but I am trying to get the example code running, and it works fine on text-only prompts, but as soon as I try to embed an image I get the following error:

```
RuntimeError: shape mismatch: value tensor of shape [64, 6656] cannot be broadcast to indexing result of shape [0, 6656]
```

I'm using the Huggingface version of the model, with code looking something like this:

```
  question = '[<IMG_PLH>]Describe the image in details:'

    tokenizer = AutoTokenizer.from_pretrained("BAAI/Emu2")
    model = AutoModelForCausalLM.from_pretrained("BAAI/Emu2",
                                                 torch_dtype=torch.bfloat16,
                                                 low_cpu_mem_usage=True,
                                                 trust_remote_code=True,
                                                 ).to("cuda").eval()

    self.tokenizer = tokenizer
    self.model = model

    images = [
      Image.open(requests.get(
        '<<an image.jpg>>',
        stream=True).raw).convert('RGB')
    ]

    inputs = self.model.build_input_ids(text=question,
                                        tokenizer=self.tokenizer,
                                        image=images)

    with torch.no_grad():
      outputs = self.model.generate(input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        image=inputs["image"].to(torch.bfloat16),
        max_new_tokens=64,
        length_penalty=-1)

    result = self.tokenizer.batch_decode(outputs, skip_special_tokens=True)

```

Any ideas?  I've been scratching my head for ages now...

**Comment by ryanzhangfan** [comment]
`question` should be a list of string. The thing is the model treats each character in `question` as a separate prompt.

**Comment by timwalls** [comment]
(facepalm)

Thank you!  I must have fiddled with or stared at every single line of code for an eternity, except that one...  In my defence I'm new at Python ;-).

Thanks again, and for the great work as well.  Happy New Year and have a great 2024!

**Comment by ryanzhangfan** [comment]
Thanks a lot. Happy New Year!

I'll close this issue. Feel free to create a new one whenever encountering any other problems.
