### ISSUE TITLE
How to use video as Emu2-chat's input? 

### ISSUE THREAD

**Issue by SANJINGSHOU14** [baaivision/Emu#63]
你好，由于显存限制，我正在使用Huggingface Version中的Quantization部署Emu2-chat，目前没有找到使用video作为输入的方法，在给出的inference的代码中，有pytorch版本的video输入，没有Huggingface版本的，请问能给出相应的代码吗？十分感谢。
```
from PIL import Image 
import requests
import torch 
from transformers import AutoModelForCausalLM, AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained("BAAI/Emu2") # "BAAI/Emu2-Chat"

model = AutoModelForCausalLM.from_pretrained(
    "BAAI/Emu2", # "BAAI/Emu2-Chat"
    load_in_4bit=True,
    trust_remote_code=True, 
    bnb_4bit_compute_dtype=torch.float16).eval()

#这里是video的话应该怎么写呢？是将[<IMG_PLH>]复制视频帧的次数然后直接跟prompt吗？求解答
query = '[<IMG_PLH>]Describe the image in details:' 
#示例代码中video的输入格式是Optional[List["PIL.Image"]]
image = Image.open("./examples/blue_black_1_top_left.jpg").convert('RGB')

inputs = model.build_input_ids(
    text=[query],
    tokenizer=tokenizer,
    image=[image]
)

with torch.no_grad():
     outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        image=inputs["image"].to(torch.float16), # should be torch.float16
        max_new_tokens=64,
        length_penalty=-1)

output_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
```

**Comment by ryanzhangfan** [comment]
对于视频输入，假设你已经抽了8帧
```
video = [Image.open(f"frame_{idx}.png").convert("RGB") for idx in range(8)]
query = "[VIDEO]" + "[<VID_PLH>]" * 8 + "Describe the video in details"

# 如果希望使用Chat方式，还需要follow chat template
system_message = ""
query = f"{system_message} [USER]: {query} [ASSISTANT]:"

inputs = model.build_input_ids(
    text=[query],
    tokenizer=tokenizer,
    video=video,
)

with torch.no_grad():
    outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        video=inputs["video"].to(torch.float16),
    )
```
其中，system message可以在[这里](https://github.com/baaivision/Emu/blob/1561aa98707d3118d50b67200d345076307c47eb/Emu2/emu/constants.py#L43)找到。

**Comment by SANJINGSHOU14** [comment]
明白了，感谢回复。
另外我想问一下如何进行连续对话，是在``query = f"{system_message} [USER]: {query} [ASSISTANT]:"``后面继续加`[USER]: {query} [ASSISTANT]:`吗？像这样：
```
query = f"{system_message} [USER]: {query1} [ASSISTANT]:[USER]: {query2} [ASSISTANT]:"
```

**Comment by ryanzhangfan** [comment]
连续对话，需要follow这个形式

`query = f"{system_message} [USER]: {query1} [ASSISTANT]: {answer1}</s>[USER]: {query2} [ASSISTANT]:"`

更具体的构建流程，可以参考这里的[代码](https://github.com/baaivision/Emu/blob/1561aa98707d3118d50b67200d345076307c47eb/Emu2/emu/chat.py#L159)

p.s. 这个函数的输入输出形式只适用于native pytorch版本的model，不能直接用于hf版本的模型。但是构建的流程可以参考，并且最终输入到LLM里的数据形式都是一样的。

**Comment by SANJINGSHOU14** [comment]
十分感谢。


> ```
> video = [Image.open(f"frame_{idx}.png").convert("RGB") for idx in range(8)]
> query = "[VIDEO]" + "[<VID_PLH>]" * 8 + "Describe the video in details"
> 
> # 如果希望使用Chat方式，还需要follow chat template
> system_message = ""
> query = f"{system_message} [USER]: {query} [ASSISTANT]:"
> 
> inputs = model.build_input_ids(
>     text=[query],
>     tokenizer=tokenizer,
>     video=video,
> )
> 
> with torch.no_grad():
>     outputs = model.generate(
>         input_ids=inputs["input_ids"],
>         attention_mask=inputs["attention_mask"],
>         video=inputs["video"].to(torch.float16),
>     )
> ```
另外，我使用前面你给的方法，在hf上使用量化模型，并输入8帧video时，报错如下：
```
Traceback (most recent call last):
  File "/xxx/Project/Emu/Emu2/quan.py", line 64, in <module>
    outputs = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/weights/modeling_emu.py", line 161, in generate
    text_embeds[image_idx] = prompt_image_embeds.to(text_embeds.device)
RuntimeError: shape mismatch: value tensor of shape [2048, 6656] cannot be broadcast to indexing result of shape [0, 6656]
```

**Comment by ryanzhangfan** [comment]
这段代码我这边跑了下是没问题的。可能需要你自己debug下，这个报错暴露出两个问题：

1、输入了8张图，但是想用这8张图的feature去替换prompt中的占位符时，没有发现图像占位符(这就是[0, 6656]中0的来源)。需要check下输入的prompt在tokenize之后是不是包含了图像占位符的token（id是32004）。可以print一下inputs["input_ids"]看下。
2、视频中的每一帧应该是64个token，8帧一共是512个token。而图像每一张是256个token，8张是2048个token。报错中[2048, 6656]表明模型把输入的视频帧当作图像来处理了。这里需要确认下输入的video在哪里处理的，以及为什么会被当作图像，而不是视频帧。确认下视频帧是否是在这个[条件](https://huggingface.co/BAAI/Emu2-Chat/blob/20ea30b04f8fee599cf97535e655c200df728501/modeling_emu.py#L163)中处理的，以及这里使用的self.v_query是否是64。但从你这个报错信息指向161行来看，应该没进到video这个条件，而是进了image那个。你可以再确认一下。

**Comment by ryanzhangfan** [comment]
> 你好，由于显存限制，我正在使用Huggingface Version中的Quantization部署Emu2-chat，目前没有找到使用video作为输入的方法，在给出的inference的代码中，有pytorch版本的video输入，没有Huggingface版本的，请问能给出相应的代码吗？十分感谢。
> 
> ```
> from PIL import Image 
> import requests
> import torch 
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> 
> tokenizer = AutoTokenizer.from_pretrained("BAAI/Emu2") # "BAAI/Emu2-Chat"
> 
> model = AutoModelForCausalLM.from_pretrained(
>     "BAAI/Emu2", # "BAAI/Emu2-Chat"
>     load_in_4bit=True,
>     trust_remote_code=True, 
>     bnb_4bit_compute_dtype=torch.float16).eval()
> 
> #这里是video的话应该怎么写呢？是将[<IMG_PLH>]复制视频帧的次数然后直接跟prompt吗？求解答
> query = '[<IMG_PLH>]Describe the image in details:' 
> #示例代码中video的输入格式是Optional[List["PIL.Image"]]
> image = Image.open("./examples/blue_black_1_top_left.jpg").convert('RGB')
> 
> inputs = model.build_input_ids(
>     text=[query],
>     tokenizer=tokenizer,
>     image=[image]
> )
> 
> with torch.no_grad():
>      outputs = model.generate(
>         input_ids=inputs["input_ids"],
>         attention_mask=inputs["attention_mask"],
>         image=inputs["image"].to(torch.float16), # should be torch.float16
>         max_new_tokens=64,
>         length_penalty=-1)
> 
> output_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
> ```

btw，这段用的模型时Emu2，而非Emu2-Chat，对于Emu2来讲，image和video frame都会encode到64个token，而不是一个256，一个64。其他的处理过程和我上一条回复的是一致。

**Comment by SANJINGSHOU14** [comment]
> 这段代码我这边跑了下是没问题的。可能需要你自己debug下，这个报错暴露出两个问题：
> 
> 1、输入了8张图，但是想用这8张图的feature去替换prompt中的占位符时，没有发现图像占位符(这就是[0, 6656]中0的来源)。需要check下输入的prompt在tokenize之后是不是包含了图像占位符的token（id是32004）。可以print一下inputs["input_ids"]看下。 2、视频中的每一帧应该是64个token，8帧一共是512个token。而图像每一张是256个token，8张是2048个token。报错中[2048, 6656]表明模型把输入的视频帧当作图像来处理了。这里需要确认下输入的video在哪里处理的，以及为什么会被当作图像，而不是视频帧。确认下视频帧是否是在这个[条件](https://huggingface.co/BAAI/Emu2-Chat/blob/20ea30b04f8fee599cf97535e655c200df728501/modeling_emu.py#L163)中处理的，以及这里使用的self.v_query是否是64。但从你这个报错信息指向161行来看，应该没进到video这个条件，而是进了image那个。你可以再确认一下。

谢谢，我去debug看看问题在哪里。

**Comment by SANJINGSHOU14** [comment]
> > 你好，由于显存限制，我正在使用Huggingface Version中的Quantization部署Emu2-chat，目前没有找到使用video作为输入的方法，在给出的inference的代码中，有pytorch版本的video输入，没有Huggingface版本的，请问能给出相应的代码吗？十分感谢。
> > ```
> > from PIL import Image 
> > import requests
> > import torch 
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > 
> > tokenizer = AutoTokenizer.from_pretrained("BAAI/Emu2") # "BAAI/Emu2-Chat"
> > 
> > model = AutoModelForCausalLM.from_pretrained(
> >     "BAAI/Emu2", # "BAAI/Emu2-Chat"
> >     load_in_4bit=True,
> >     trust_remote_code=True, 
> >     bnb_4bit_compute_dtype=torch.float16).eval()
> > 
> > #这里是video的话应该怎么写呢？是将[<IMG_PLH>]复制视频帧的次数然后直接跟prompt吗？求解答
> > query = '[<IMG_PLH>]Describe the image in details:' 
> > #示例代码中video的输入格式是Optional[List["PIL.Image"]]
> > image = Image.open("./examples/blue_black_1_top_left.jpg").convert('RGB')
> > 
> > inputs = model.build_input_ids(
> >     text=[query],
> >     tokenizer=tokenizer,
> >     image=[image]
> > )
> > 
> > with torch.no_grad():
> >      outputs = model.generate(
> >         input_ids=inputs["input_ids"],
> >         attention_mask=inputs["attention_mask"],
> >         image=inputs["image"].to(torch.float16), # should be torch.float16
> >         max_new_tokens=64,
> >         length_penalty=-1)
> > 
> > output_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
> > ```
> 
> btw，这段代码用的模型时Emu2，而非Emu2-Chat，对于Emu2来讲，image和video frame都会encode到64个token，而不是一个256，一个64。其他的处理过程和我上一条回复的是一致。

这段代码是提issue时从这个repo直接复制的，实际使用时用的Emu2-chat，再次感谢！

**Comment by SANJINGSHOU14** [comment]
你好，检查完bug发现是生成`inputs`时将video传给了image，现在已经正常跑通，我还想咨询两个问题：
1. pytorch版本的模型正常部署Emu2-chat-37B的模型对显存的要求大概是多少（8-frame-1600x900视频输入的话）；
2. Emu2模型有多机多卡的推理代码吗？如果有的话方便公开吗？

再次感谢你的耐心回答！

**Comment by ryanzhangfan** [comment]
1. **显存**：如果要部署bf16版本的话，推荐要有120GB的显存(80GB大概只能)。
2. **单机多卡**：Emu2系列现在已经支持单机多卡的推理，native pytorch版本和huggingface版本分别在github和huggingface主页的README.md里都有如何开启多卡的教程。
3. **多机多卡**：多机的代码目前和训练代码深度耦合，我们还在整理当中，计划后续整理完毕后会放出。关于多机，我们也是使用开源框架deepspeed来实现。因为模型直接继承于nn.Module，你也可以自行用deepspeed或者其他框架来实现。

**Comment by SANJINGSHOU14** [comment]
明白了，再次感谢
