### ISSUE TITLE
How to evaluate REC tasks

### ISSUE THREAD

**Issue by theFool32** [baaivision/Emu#66]
Hi, thanks for this enlightening work. 

I noticed on the emu-2 readme page that the emu-chat method achieved very surprising results on several REC datasets. Since the demo does not show that emu-2 can ouput the bounding box coordinate, I wonder how this is evaluated.

**Comment by ryanzhangfan** [comment]
We have provided a simple chat example in grounding scenario in [README.md](https://github.com/baaivision/Emu/tree/main/Emu2#emu2--emu2-chat-1). The output coordinates are in the format of [x1, y1, x2, y2].
![image](https://github.com/baaivision/Emu/assets/16065909/5a5523f4-3b6f-4655-b866-9b7ec0bd4c77)

p.s. Currently ONLY native pytorch model has the off-the-shelf interface. If you are using the HF version, you need to migrate the corresponding codes manually.
