### ISSUE TITLE
Emu2-Gen 所需的显存是多少啊

### ISSUE THREAD

**Issue by DaBaiTuu** [baaivision/Emu#67]

**Comment by DaBaiTuu** [comment]
请问有没有对于低硬件平台的优化或计划，有的话有说明文档么

**Comment by ryanzhangfan** [comment]
#### 显存占用
1. 如果使用bf16精度，那么Emu2-Gen模型需要占用77GB显存，inference建议需要具有至少80GB显存（包含模型占用的77GB）。
2. 如果LLM的部分使用int4量化，则需要占用大约27G显存。

#### 低硬件平台优化
由于人力有限，我们暂时没有在低硬件平台上优化的计划。

**Comment by DaBaiTuu** [comment]
> #### 显存占用
> 
>     1. 如果使用bf16精度，那么Emu2-Gen模型需要占用77GB显存，inference建议需要具有至少80GB显存（包含模型占用的77GB）。
> 
>     2. 如果MLLM的部分使用int4量化，则需要占用大约27G显存。
> 
> 
> #### 低硬件平台优化
> 
> 由于人力有限，我们暂时没有在低硬件平台上优化的计划。

好的好的谢谢，本来是想本地部署下试试的
