### ISSUE TITLE
能不能结合 emu2-chat 和 emu2-gen

### ISSUE THREAD

**Issue by prefixRAINSTARsuffix** [baaivision/Emu#69]
生成文本和生成图像需要两个不同的模型，能不能一个模型实现这两个功能。我看你的训练模式是同时训练文本生成和图像生成的（分类loss和回归loss），为什么推理的时候要分两个模型呢 ？

**Comment by Quan-Sun** [comment]
你好，很高兴你关注我们的工作。Emu2本身是预训练模型，在预训练的时候会同时训练文本和图像生成。Emu2-Chat和Emu2-Gen是Emu2在不同数据上finetune的结果，finetune的时候只有一个训练目标，对于Emu2-Chat只优化文本的loss，对于Emu2-Gen只优化图像/视频的loss。也可以把图像生成构造成chat格式的数据，同时去finetune模型，但是这里的训练的难度会更大，欢迎感兴趣的开发者进行实验。我们通过Emu2-Chat和Emu2-Gen表明Emu2经过finetune可以在对话和图像/视频生成上有非常好的效果，开发者也可以用Emu2在不同的数据上finetune得到其他性能很好的模型。我们很欢迎越来越多的开发者使用Emu2去开发出更多新的能力的新模型。

**Comment by SxJyJay** [comment]
您好，对于emu的autoregressive的image regression训练有一些问题想请教您。我个人理解这部分在训练时首先需要冻结ViT和Casual Transformer以提供稳定的连续视觉特征。在训练的第i个timestep，模型输入从真实图像的第i个patch中提取的visual
 feature，用于预测第i+1个patch的visual feature。在测试的第i个timestep，模型输入上一步预测出的第i个patch中的feature作为当前的输入。如果是这种操作的话，是否会存在由于训练和测试时第i个timestep输入feature由于真实和预测存在的gap而导致测试时错误累积的问题呢？
