### ISSUE TITLE
How much video memory do I need for reasoning?

### ISSUE THREAD

**Issue by wccccp** [baaivision/Emu#7]
I have a 3090nvidia graphics card, is it possible to do inference?

**Comment by yqy2001** [comment]
Inference costs ~30GB and it depends on the sequence length. An A100-40G or A6000 is recommended. 

We may provide a quantized version that can run on a 3090 in the future, but I cannot promise now.

**Comment by wccccp** [comment]
> Inference costs ~30GB and it depends on the sequence length. An A100-40G or A6000 is recommended.
> 
> We may provide a quantized version that can run on a 3090 in the future, but I cannot promise now.

thank you
