### ISSUE TITLE
Gibberish response while trying sample inference script 

### ISSUE THREAD

**Issue by charush12** [baaivision/Emu#8]
Hi Team,

Thanks for your amazing work, unfortunately, I'm unable to get the correct response using the inference.py with a sample image in the examples folder,
<img width="1181" alt="Screenshot" src="https://github.com/baaivision/Emu/assets/32143480/b42ba025-28b1-49ff-a1bc-66dc7b538349">

**Comment by yqy2001** [comment]
Can you provide the message of loading checkpoint? I guess you loaded the pretrained **Emu** instead of instruction-tuned **Emu-I**. The inference code is for **Emu-I**.

**Comment by charush12** [comment]
Thanks or replying, and yes that was the issue

**Comment by yqy2001** [comment]
We added inference example for the pretrained **Emu**. You can pull the latest commit and run this [command](https://github.com/baaivision/Emu/blob/4291e3792b30514d78755a4019133c9629271c5d/README.md?plain=1#L59) for an example of in-context learning.

**Comment by charush12** [comment]
Thanks great, is there a prompt template available for the in-context learining ?

**Comment by yqy2001** [comment]
> Thanks great, is there a prompt template available for the in-context learining ?

No prompt template is needed, you just need to concat several samples that serve as examples for in-context learning, please check out the code [here](https://github.com/baaivision/Emu/blob/36d7ce7eb07272be3241086df0e37b0bac1889e5/inference.py#L127).
