### ISSUE TITLE
Request for Detailed Explanation of Causal Transformer Module

### ISSUE THREAD

**Issue by pixeli99** [baaivision/Emu#9]
Dear Authors,

I've been reading your work on the Causal Transformer module and I find it fascinating. However, I'm having difficulty understanding some aspects of it, especially how the module transforms 2D spatial visual signals to 1D causal sequences in a latent space.

Specifically, I'm struggling to understand the process detailed in this part of your paper:

"Given an image I with its encodings g(I) from EVA-CLIP, Causal Transformer accepts randomly initialized embeddings {e1,e2,...,eN} as input, and outputs N embeddings {z1,z2,...,zN} that capture the causal dependency of the given image: z1,z2,...,zN = CausalTransformer (g(I),{e1,e2,...,eN}) (1)"

Could you please provide a more detailed explanation or possibly a diagrammatic illustration of this process? I believe this would greatly aid my understanding, as well as that of other readers who may be having a similar issue.

**Comment by yqy2001** [comment]
Thank you for your suggestions, we will add an illustration in the next version of our paper.

A brief explanation is provided here. The architecture of Causal Transformer is similar to the decoder module of raw Transformer:
<img src="https://github.com/baaivision/Emu/assets/55196500/4a183d71-a8c6-4c81-9791-0f982ec455ac" style="zoom: 5%;" />
i.e., each block consists of three layers, masked (causal) self-attention, cross-attention, and feed-forward layer.

The process of aggregating information from 2D spatial visual signals into 1D causal sequence layer by layer:
* Masked (causal) self-attention layer: we feed N leanable tokens (vectors) into this layer as Q, K and V. The output tokens encode causal dependencies among each other. 
* Cross-attention layer: the outputs from the previous causal self-attention layer serve as Q, while image features from EVA-CLIP serve as K and V. Each token can see all image features and extract information from them.
* The feed-forward layer: a standard feed-forward layer.

Through this process, the input vectors aggregate information from the image features while encoding causal dependency among each other.

Please let me know if you have any questions or if anything I said was unclear.
